run_mode = "debug"

[app]
    page_size = 10
    jwt_secret = "23347$040412"

[server]
    http_port = 8000
    read_timeout = 60
    write_timeout = 60

[database]
    type = "mysql"
    host = "127.0.0.1:3306"
    user = "root"
    password = "123456"
#    host = "192.168.0.235:3355"
#    user = "cishop"
#    password = "fuyuan1906"
    name = "service_items"
    table_prefix = ""