run_mode = "release"

[server]
    http_port = 8000
    read_timeout = 60
    write_timeout = 60

[database]
    [database.master]
        [database.master.service_items]
            type = "mysql"
            host = "127.0.0.1:3306"
            user = "root"
            password = "123456"
            #    host = "192.168.0.235:3355"
            #    user = "cishop"
            #    password = "fuyuan1906"
            name = "service_items"
            table_prefix = ""
            need_connection_pool = true
            Max_idle_connections = 10
            max_open_connections = 100
    [database.slave]
        [database.slave.service_items]
            type = "mysql"
            host = "127.0.0.1:3306"
            user = "root"
            password = "123456"
        #    host = "192.168.0.235:3355"
        #    user = "cishop"
        #    password = "fuyuan1906"
            name = "service_items"
            table_prefix = ""
            need_connection_pool = false
            max_idle_connections = 0
            max_open_connections = 0

[rabbitmq]
    host = "localhost"
    port = 5672
    user = "guest"
    password = "guest"
    vhost = "/"

[log]
    [log.access_log.log_config]
        file_path = "./logs/access_log"
        file_name = "access.log"
    [log.error_log.log_config]
        file_path = "./logs/error_log"
        file_name = "error.log"